In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("C:/Users/admin/Downloads/heart.xls")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [3]:
from sklearn.neural_network import MLPClassifier 
from sklearn.neural_network import MLPRegressor 
# Import necessary modules 
from sklearn.model_selection import train_test_split 
from sklearn.metrics import mean_squared_error 
from math import sqrt 
from sklearn.metrics import r2_score 

In [4]:
df.describe().transpose()

count        mean        std    min    25%    50%    75%    max
age       1025.0   54.434146   9.072290   29.0   48.0   56.0   61.0   77.0
sex       1025.0    0.695610   0.460373    0.0    0.0    1.0    1.0    1.0
cp        1025.0    0.942439   1.029641    0.0    0.0    1.0    2.0    3.0
trestbps  1025.0  131.611707  17.516718   94.0  120.0  130.0  140.0  200.0
chol      1025.0  246.000000  51.592510  126.0  211.0  240.0  275.0  564.0
fbs       1025.0    0.149268   0.356527    0.0    0.0    0.0    0.0    1.0
restecg   1025.0    0.529756   0.527878    0.0    0.0    1.0    1.0    2.0
thalach   1025.0  149.114146  23.005724   71.0  132.0  152.0  166.0  202.0
exang     1025.0    0.336585   0.472772    0.0    0.0    0.0    1.0    1.0
oldpeak   1025.0    1.071512   1.175053    0.0    0.0    0.8    1.8    6.2
slope     1025.0    1.385366   0.617755    0.0    1.0    1.0    2.0    2.0
ca        1025.0    0.754146   1.030798    0.0    0.0    0.0    1.0    4.0
thal      1025.0    2.323902   0.620660    0.0    2.0    2.0    3.0    3.0
target    1025.0    0.513171   0.500070    0.0    0.0    1.0    1.0    1.0

In [6]:
target_column = ['target']
predictors = list(set(list(df.columns))-set(target_column)) 
df[predictors] = df[predictors]/df[predictors].max() 
X = df[predictors].values 
y = df[target_column].values 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30,  random_state=40) 
print(X_train.shape)
print(X_test.shape)

(717, 13)
(308, 13)


In [7]:
from sklearn.neural_network import MLPClassifier 
mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu',  solver='adam', max_iter=500) 
mlp.fit(X_train,y_train) 
predict_train = mlp.predict(X_train) 
predict_test = mlp.predict(X_test) 
from sklearn.metrics import classification_report,confusion_matrix 
print(confusion_matrix(y_train,predict_train)) 
print(classification_report(y_train,predict_train)) 
print(confusion_matrix(y_test,predict_test)) 
print(classification_report(y_test,predict_test)) 

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[311  35]
 [ 36 335]]
              precision    recall  f1-score   support

           0       0.90      0.90      0.90       346
           1       0.91      0.90      0.90       371

    accuracy                           0.90       717
   macro avg       0.90      0.90      0.90       717
weighted avg       0.90      0.90      0.90       717

[[131  22]
 [ 20 135]]
              precision    recall  f1-score   support

           0       0.87      0.86      0.86       153
           1       0.86      0.87      0.87       155

    accuracy                           0.86       308
   macro avg       0.86      0.86      0.86       308
weighted avg       0.86      0.86      0.86       308



C:\ProgramData\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [8]:
from sklearn.neural_network import MLPClassifier 
mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='identity',  solver='adam', max_iter=500) 
mlp.fit(X_train,y_train)
predict_train = mlp.predict(X_train) 
predict_test = mlp.predict(X_test) 
from sklearn.metrics import classification_report,confusion_matrix 
print(confusion_matrix(y_train,predict_train)) 
print(classification_report(y_train,predict_train)) 
print(confusion_matrix(y_test,predict_test)) 
print(classification_report(y_test,predict_test)) 
from sklearn.neural_network import MLPClassifier 
mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='tanh',  solver='adam', max_iter=500) 
mlp.fit(X_train,y_train) 
predict_train = mlp.predict(X_train) 
predict_test = mlp.predict(X_test) 
from sklearn.metrics import classification_report,confusion_matrix 
print(confusion_matrix(y_train,predict_train)) 
print(classification_report(y_train,predict_train)) 
print(confusion_matrix(y_test,predict_test)) 
print(classification_report(y_test,predict_test))

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[283  63]
 [ 40 331]]
              precision    recall  f1-score   support

           0       0.88      0.82      0.85       346
           1       0.84      0.89      0.87       371

    accuracy                           0.86       717
   macro avg       0.86      0.86      0.86       717
weighted avg       0.86      0.86      0.86       717

[[125  28]
 [ 19 136]]
              precision    recall  f1-score   support

           0       0.87      0.82      0.84       153
           1       0.83      0.88      0.85       155

    accuracy                           0.85       308
   macro avg       0.85      0.85      0.85       308
weighted avg       0.85      0.85      0.85       308



C:\ProgramData\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[309  37]
 [ 29 342]]
              precision    recall  f1-score   support

           0       0.91      0.89      0.90       346
           1       0.90      0.92      0.91       371

    accuracy                           0.91       717
   macro avg       0.91      0.91      0.91       717
weighted avg       0.91      0.91      0.91       717

[[129  24]
 [ 14 141]]
              precision    recall  f1-score   support

           0       0.90      0.84      0.87       153
           1       0.85      0.91      0.88       155

    accuracy                           0.88       308
   macro avg       0.88      0.88      0.88       308
weighted avg       0.88      0.88      0.88       308



C:\ProgramData\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [9]:
from sklearn.neural_network import MLPClassifier 
mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='logistic',  solver='adam', max_iter=500) 
mlp.fit(X_train,y_train) 
predict_train = mlp.predict(X_train) 
predict_test = mlp.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix 
print(confusion_matrix(y_train,predict_train)) 
print(classification_report(y_train,predict_train)) 
print(confusion_matrix(y_test,predict_test)) 
print(classification_report(y_test,predict_test))

[[  0 346]
 [  0 371]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       346
           1       0.52      1.00      0.68       371

    accuracy                           0.52       717
   macro avg       0.26      0.50      0.34       717
weighted avg       0.27      0.52      0.35       717

[[  0 153]
 [  0 155]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       153
           1       0.50      1.00      0.67       155

    accuracy                           0.50       308
   macro avg       0.25      0.50      0.33       308
weighted avg       0.25      0.50      0.34       308



C:\ProgramData\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469:

In [10]:
from sklearn.neural_network import MLPClassifier 
mlp = MLPClassifier(hidden_layer_sizes=(10,10,10), activation='relu',  solver='adam', max_iter=500) 
mlp.fit(X_train,y_train) 
predict_train = mlp.predict(X_train) 
predict_test = mlp.predict(X_test) 
from sklearn.metrics import classification_report,confusion_matrix 
print(confusion_matrix(y_train,predict_train)) 
print(classification_report(y_train,predict_train)) 
print(confusion_matrix(y_test,predict_test)) 
print(classification_report(y_test,predict_test)) 

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[307  39]
 [ 37 334]]
              precision    recall  f1-score   support

           0       0.89      0.89      0.89       346
           1       0.90      0.90      0.90       371

    accuracy                           0.89       717
   macro avg       0.89      0.89      0.89       717
weighted avg       0.89      0.89      0.89       717

[[131  22]
 [ 16 139]]
              precision    recall  f1-score   support

           0       0.89      0.86      0.87       153
           1       0.86      0.90      0.88       155

    accuracy                           0.88       308
   macro avg       0.88      0.88      0.88       308
weighted avg       0.88      0.88      0.88       308



C:\ProgramData\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
